apiVersion: v1
kind: Pod
metadata:
  name: conversor
  labels:
    name: conversor
spec:
  containers:
  - name: convtemp
    image: pestana1984/conversao-temperatura:latest
    ports:
    - containerPort: 8080
